/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AccessDeniedRouteImport } from './routes/access-denied'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'
import { Route as AppAppealsRouteImport } from './routes/_app.appeals'
import { Route as AppBetaRouteImport } from './routes/_app.beta'
import { Route as AppMonitoringRouteImport } from './routes/_app.monitoring'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppRidesRouteImport } from './routes/_app.rides'
import { Route as AppSafetyRouteImport } from './routes/_app.safety'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppStandbyRouteImport } from './routes/_app.standby'
import { Route as AppTeamRouteImport } from './routes/_app.team'
import { Route as AppTicketsRouteImport } from './routes/_app.tickets'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppVerificationsRouteImport } from './routes/_app.verifications'
import { Route as AppUsersUserIdRouteImport } from './routes/_app.users.$userId'
import { Route as AppVerificationsVerificationIdRouteImport } from './routes/_app.verifications.$verificationId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessDeniedRoute = AccessDeniedRouteImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAppealsRoute = AppAppealsRouteImport.update({
  id: '/appeals',
  path: '/appeals',
  getParentRoute: () => AppRoute,
} as any)
const AppBetaRoute = AppBetaRouteImport.update({
  id: '/beta',
  path: '/beta',
  getParentRoute: () => AppRoute,
} as any)
const AppMonitoringRoute = AppMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppRidesRoute = AppRidesRouteImport.update({
  id: '/rides',
  path: '/rides',
  getParentRoute: () => AppRoute,
} as any)
const AppSafetyRoute = AppSafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppStandbyRoute = AppStandbyRouteImport.update({
  id: '/standby',
  path: '/standby',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppTicketsRoute = AppTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppVerificationsRoute = AppVerificationsRouteImport.update({
  id: '/verifications',
  path: '/verifications',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersUserIdRoute = AppUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AppUsersRoute,
} as any)
const AppVerificationsVerificationIdRoute =
  AppVerificationsVerificationIdRouteImport.update({
    id: '/$verificationId',
    path: '/$verificationId',
    getParentRoute: () => AppVerificationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/login': typeof LoginRoute
  '/analytics': typeof AppAnalyticsRoute
  '/appeals': typeof AppAppealsRoute
  '/beta': typeof AppBetaRoute
  '/monitoring': typeof AppMonitoringRoute
  '/reports': typeof AppReportsRoute
  '/rides': typeof AppRidesRoute
  '/safety': typeof AppSafetyRoute
  '/settings': typeof AppSettingsRoute
  '/standby': typeof AppStandbyRoute
  '/team': typeof AppTeamRoute
  '/tickets': typeof AppTicketsRoute
  '/users': typeof AppUsersRouteWithChildren
  '/verifications': typeof AppVerificationsRouteWithChildren
  '/users/$userId': typeof AppUsersUserIdRoute
  '/verifications/$verificationId': typeof AppVerificationsVerificationIdRoute
}
export interface FileRoutesByTo {
  '/access-denied': typeof AccessDeniedRoute
  '/login': typeof LoginRoute
  '/analytics': typeof AppAnalyticsRoute
  '/appeals': typeof AppAppealsRoute
  '/beta': typeof AppBetaRoute
  '/monitoring': typeof AppMonitoringRoute
  '/reports': typeof AppReportsRoute
  '/rides': typeof AppRidesRoute
  '/safety': typeof AppSafetyRoute
  '/settings': typeof AppSettingsRoute
  '/standby': typeof AppStandbyRoute
  '/team': typeof AppTeamRoute
  '/tickets': typeof AppTicketsRoute
  '/users': typeof AppUsersRouteWithChildren
  '/verifications': typeof AppVerificationsRouteWithChildren
  '/': typeof AppIndexRoute
  '/users/$userId': typeof AppUsersUserIdRoute
  '/verifications/$verificationId': typeof AppVerificationsVerificationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/access-denied': typeof AccessDeniedRoute
  '/login': typeof LoginRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/appeals': typeof AppAppealsRoute
  '/_app/beta': typeof AppBetaRoute
  '/_app/monitoring': typeof AppMonitoringRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/rides': typeof AppRidesRoute
  '/_app/safety': typeof AppSafetyRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/standby': typeof AppStandbyRoute
  '/_app/team': typeof AppTeamRoute
  '/_app/tickets': typeof AppTicketsRoute
  '/_app/users': typeof AppUsersRouteWithChildren
  '/_app/verifications': typeof AppVerificationsRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/users/$userId': typeof AppUsersUserIdRoute
  '/_app/verifications/$verificationId': typeof AppVerificationsVerificationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-denied'
    | '/login'
    | '/analytics'
    | '/appeals'
    | '/beta'
    | '/monitoring'
    | '/reports'
    | '/rides'
    | '/safety'
    | '/settings'
    | '/standby'
    | '/team'
    | '/tickets'
    | '/users'
    | '/verifications'
    | '/users/$userId'
    | '/verifications/$verificationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/access-denied'
    | '/login'
    | '/analytics'
    | '/appeals'
    | '/beta'
    | '/monitoring'
    | '/reports'
    | '/rides'
    | '/safety'
    | '/settings'
    | '/standby'
    | '/team'
    | '/tickets'
    | '/users'
    | '/verifications'
    | '/'
    | '/users/$userId'
    | '/verifications/$verificationId'
  id:
    | '__root__'
    | '/_app'
    | '/access-denied'
    | '/login'
    | '/_app/analytics'
    | '/_app/appeals'
    | '/_app/beta'
    | '/_app/monitoring'
    | '/_app/reports'
    | '/_app/rides'
    | '/_app/safety'
    | '/_app/settings'
    | '/_app/standby'
    | '/_app/team'
    | '/_app/tickets'
    | '/_app/users'
    | '/_app/verifications'
    | '/_app/'
    | '/_app/users/$userId'
    | '/_app/verifications/$verificationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AccessDeniedRoute: typeof AccessDeniedRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-denied': {
      id: '/access-denied'
      path: '/access-denied'
      fullPath: '/access-denied'
      preLoaderRoute: typeof AccessDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/appeals': {
      id: '/_app/appeals'
      path: '/appeals'
      fullPath: '/appeals'
      preLoaderRoute: typeof AppAppealsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/beta': {
      id: '/_app/beta'
      path: '/beta'
      fullPath: '/beta'
      preLoaderRoute: typeof AppBetaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/monitoring': {
      id: '/_app/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof AppMonitoringRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rides': {
      id: '/_app/rides'
      path: '/rides'
      fullPath: '/rides'
      preLoaderRoute: typeof AppRidesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/safety': {
      id: '/_app/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof AppSafetyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/standby': {
      id: '/_app/standby'
      path: '/standby'
      fullPath: '/standby'
      preLoaderRoute: typeof AppStandbyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/team': {
      id: '/_app/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tickets': {
      id: '/_app/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof AppTicketsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/verifications': {
      id: '/_app/verifications'
      path: '/verifications'
      fullPath: '/verifications'
      preLoaderRoute: typeof AppVerificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users/$userId': {
      id: '/_app/users/$userId'
      path: '/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof AppUsersUserIdRouteImport
      parentRoute: typeof AppUsersRoute
    }
    '/_app/verifications/$verificationId': {
      id: '/_app/verifications/$verificationId'
      path: '/$verificationId'
      fullPath: '/verifications/$verificationId'
      preLoaderRoute: typeof AppVerificationsVerificationIdRouteImport
      parentRoute: typeof AppVerificationsRoute
    }
  }
}

interface AppUsersRouteChildren {
  AppUsersUserIdRoute: typeof AppUsersUserIdRoute
}

const AppUsersRouteChildren: AppUsersRouteChildren = {
  AppUsersUserIdRoute: AppUsersUserIdRoute,
}

const AppUsersRouteWithChildren = AppUsersRoute._addFileChildren(
  AppUsersRouteChildren,
)

interface AppVerificationsRouteChildren {
  AppVerificationsVerificationIdRoute: typeof AppVerificationsVerificationIdRoute
}

const AppVerificationsRouteChildren: AppVerificationsRouteChildren = {
  AppVerificationsVerificationIdRoute: AppVerificationsVerificationIdRoute,
}

const AppVerificationsRouteWithChildren =
  AppVerificationsRoute._addFileChildren(AppVerificationsRouteChildren)

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAppealsRoute: typeof AppAppealsRoute
  AppBetaRoute: typeof AppBetaRoute
  AppMonitoringRoute: typeof AppMonitoringRoute
  AppReportsRoute: typeof AppReportsRoute
  AppRidesRoute: typeof AppRidesRoute
  AppSafetyRoute: typeof AppSafetyRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStandbyRoute: typeof AppStandbyRoute
  AppTeamRoute: typeof AppTeamRoute
  AppTicketsRoute: typeof AppTicketsRoute
  AppUsersRoute: typeof AppUsersRouteWithChildren
  AppVerificationsRoute: typeof AppVerificationsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAppealsRoute: AppAppealsRoute,
  AppBetaRoute: AppBetaRoute,
  AppMonitoringRoute: AppMonitoringRoute,
  AppReportsRoute: AppReportsRoute,
  AppRidesRoute: AppRidesRoute,
  AppSafetyRoute: AppSafetyRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStandbyRoute: AppStandbyRoute,
  AppTeamRoute: AppTeamRoute,
  AppTicketsRoute: AppTicketsRoute,
  AppUsersRoute: AppUsersRouteWithChildren,
  AppVerificationsRoute: AppVerificationsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AccessDeniedRoute: AccessDeniedRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
